version: "3.8"
services:
  langchat-test-db:
    image: postgres:15.2
    environment:
      - POSTGRES_DB=test_langchat
      - POSTGRES_USER=langteam
      - POSTGRES_PASSWORD=Aa1234
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "langchat", "-U", "langteam" ]
      interval: 10s
      timeout: 5s
      retries: 5

  langchat-test-flyway:
    image: narutosimaha/flyway-langchat-test
    # command: -url=jdbc:postgresql://postgres:5432/ejabberd -user=ejabberd -password=ejabberd_password -connectRetries=60 migrate
    environment:
      - DATABASE_NAME=test_langchat
      - DATABASE_URL=jdbc:postgresql://langchat-test-db:5432
      - POSTGRES_USER=langteam
      - POSTGRES_PASSWORD=Aa1234
    # volumes:
    #   - ./lec-db/langchat/sql:/flyway/sql
    depends_on:
      - langchat-test-db

volumes:
  pgdata: