version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file-handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: "/home/vutl/Documents/Thesis/IM/ejjaberd/lec-chathelper/lec_chathelper/chat/chatworker/worker.log"
    encoding: "utf8"
loggers:
  chat:
    level: DEBUG
    handlers: [file-handler]
root:
  level: DEBUG
  handlers: [file-handler, console]

disable_existing_loggers: False