# Generated by Django 4.0 on 2023-05-06 08:14

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUsers',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('serverkey', models.TextField()),
                ('salt', models.TextField()),
                ('iterationcount', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('langid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('locale_code', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notibox',
            fields=[
                ('boxid', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'notibox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rosterusers',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('jid', models.TextField()),
                ('nick', models.TextField()),
                ('subscription', models.CharField(max_length=1)),
                ('ask', models.CharField(max_length=1)),
                ('askmessage', models.TextField()),
                ('server', models.CharField(max_length=1)),
                ('subscribe', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'rosterusers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.UUIDField(primary_key=True, serialize=False)),
                ('longtt', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latt', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(blank=True, max_length=5, null=True)),
                ('introduction', models.CharField(blank=True, max_length=1024, null=True)),
                ('native_level', models.IntegerField(blank=True, null=True)),
                ('is_tutor', models.BooleanField(blank=True, null=True)),
                ('is_restrict', models.BooleanField(blank=True, null=True)),
                ('is_removed', models.BooleanField(blank=True, null=True)),
                ('temp_token', models.CharField(blank=True, max_length=128, null=True)),
                ('token_iat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vcard',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('vcard', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'vcard',
                'managed': False,
            },
        ),
    ]
